CREATE DATABASE ecommerce_db;
USE ecommerce_db;

-- Given Total Rows
SELECT COUNT(*) AS total_rows
FROM ecommerce_orders;

-- 1. Business Overview
-- Purpose: Overall e-commerce business performance
SELECT
    COUNT(DISTINCT order_id) AS total_orders,
    SUM(amount) AS total_revenue,
    SUM(qty) AS total_quantity
FROM ecommerce_orders;
-- Hoga: total orders + revenue + quantity.

-- 2. Category-wise Revenue
-- Purpose: Find revenue generated by each product category
SELECT
    category,
    SUM(amount) AS revenue
FROM ecommerce_orders
GROUP BY category
ORDER BY revenue DESC;
-- Hoga: kaunsi category sabse zyada revenue la rahi hai.

--  3. State-wise Revenue
-- Purpose: Find top-performing Indian states by revenue
SELECT
    ship_state,
    SUM(amount) AS revenue
FROM ecommerce_orders
GROUP BY ship_state
ORDER BY revenue DESC
LIMIT 10;
-- Hoga: top 10 states.

-- 4. Monthly Revenue
-- Purpose: Analyze monthly sales trend
SELECT
    DATE_FORMAT(date, '%Y-%m') AS month,
    SUM(amount) AS revenue
FROM ecommerce_orders
GROUP BY DATE_FORMAT(date, '%Y-%m')
ORDER BY month;
-- Hoga: kis month me sales kitni hui.

-- 5. Order Status Analysis
-- Purpose: Understand order status distribution
SELECT
    status,
    COUNT(*) AS total_rows
FROM ecommerce_orders
GROUP BY status
ORDER BY total_rows DESC;
-- Hoga: shipped, cancelled, returned etc. ka count.

-- 6. Fulfilment Analysis
-- Purpose: Compare Amazon and Merchant fulfilment
SELECT
    fulfilment,
    COUNT(*) AS total_rows,
    SUM(amount) AS revenue
FROM ecommerce_orders
GROUP BY fulfilment
ORDER BY revenue DESC;
-- Hoga: Amazon vs Merchant performance.

-- 7. Top 10 Products
-- Purpose: Find top 10 products by revenue
SELECT
    sku,
    SUM(amount) AS revenue,
    SUM(qty) AS quantity_sold
FROM ecommerce_orders
GROUP BY sku
ORDER BY revenue DESC
LIMIT 10;
-- Hoga: highest revenue wale products.

-- 8. Average Order Value (AOV)
-- Yahan important hai: same order ki multiple rows ho sakti hain, isliye pehle order-level amount calculate karenge.
-- Purpose: Calculate average value of one order

WITH order_value AS (
    SELECT
        order_id,
        SUM(amount) AS order_amount
    FROM ecommerce_orders
    GROUP BY order_id
)
SELECT
    AVG(order_amount) AS average_order_value
FROM order_value;
-- Hoga: average customer ek order me kitna spend karta hai.

-- 9. B2B vs Retail
-- Purpose: Compare B2B and regular customer orders
SELECT
    b2b,
    COUNT(DISTINCT order_id) AS total_orders,
    SUM(amount) AS revenue
FROM ecommerce_orders
GROUP BY b2b;
-- Hoga: B2B aur normal sales ka comparison.

-- 10. Promotion Analysis
-- Purpose: Compare orders with and without promotions
SELECT
    CASE
        WHEN promotion_ids = 'No Promotion' THEN 'No Promotion'
        ELSE 'Promotion Used'
    END AS promotion_type,
    COUNT(DISTINCT order_id) AS total_orders,
    SUM(amount) AS revenue
FROM ecommerce_orders
GROUP BY promotion_type;
-- Hoga: promotion use karne wale orders vs non-promotion orders.

-- 11. Shipping Service Analysis
-- Purpose: Compare Expedited and Standard shipping
SELECT
    ship_service_level,
    COUNT(DISTINCT order_id) AS total_orders,
    SUM(amount) AS revenue
FROM ecommerce_orders
GROUP BY ship_service_level
ORDER BY revenue DESC;
-- Hoga: Expedited vs Standard performance.

-- 12. Cancelled Orders & Revenue
-- Purpose: Measure cancelled orders and their associated amount
SELECT
    COUNT(DISTINCT order_id) AS cancelled_orders,
    SUM(amount) AS cancelled_amount
FROM ecommerce_orders
WHERE status = 'Cancelled';
-- Hoga: cancellation ka business impact.

-- 13. Category + Order Status
-- Purpose: Understand category performance by order status
SELECT
    category,
    status,
    COUNT(DISTINCT order_id) AS orders,
    SUM(amount) AS revenue
FROM ecommerce_orders
GROUP BY category, status
ORDER BY category, revenue DESC;
-- Hoga: har category me shipped/cancelled/returned kitne hain.

--  14. CTE — Advanced SQL
-- Purpose: Find high-revenue categories using a CTE
WITH category_sales AS (
    SELECT
        category,
        SUM(amount) AS revenue
    FROM ecommerce_orders
    WHERE status IN ('Shipped', 'Shipped - Delivered to Buyer')
    GROUP BY category
)

SELECT
    category,
    revenue
FROM category_sales
WHERE revenue > 100000
ORDER BY revenue DESC;
-- Hoga: pehle category revenue calculate, phir ₹1 lakh se upar wali categories.

-- 15. Window Function — Product Ranking
-- Purpose: Rank products within each category by revenue

SELECT
    category,
    sku,
    SUM(amount) AS revenue,
    RANK() OVER (
        PARTITION BY category
        ORDER BY SUM(amount) DESC
    ) AS product_rank
FROM ecommerce_orders
WHERE status IN ('Shipped', 'Shipped - Delivered to Buyer')
GROUP BY category, sku;

-- Hoga: har category ka #1, #2, #3 product pata chalega.